server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle: 0
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:mem:test
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 359027063032-4fbsa76omb88nk8lka6j1qi4gleg2nds.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/login/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          kakao:
            clientId: c34541d366f8d1e608583d309e7de22f
            client-secret: u5bIra6EfhHLHDq4jeYVq1FkBG0V0jA5
            redirect-uri: "{baseUrl}/login/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: kakao
          naver:
            clientId: o6Aui1II8Col5bA9e0wX
            client-secret: YRBXnrJF4H
            redirect-uri: "{baseUrl}/login/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
app:
  auth:
    token:
      secret-key: InKCDRi9NKQJYjVjab075dVkXcFdBE0L
      refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect