app:
  auth:
    token:
      secret-key: InKCDRi9NKQJYjVjab075dVkXcFdBE0L
      refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect