version: "3"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qr_service_app
      - MYSQL_DATABASE=qr
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"